### ISSUE TITLE
NameError: name 'exclude_tables' is not defined

### ISSUE THREAD

**Issue by sneak** [john-g-g/sqlite2json#2]
```
tyrell:sms▻ sqlite2json sms.db
Traceback (most recent call last):
  File "/Users/jp/Library/homebrew/bin/sqlite2json", line 9, in <module>
    load_entry_point('sqlite2json==1.0.0', 'console_scripts', 'sqlite2json')()
  File "/Users/jp/Library/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jp/Library/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2709, in load_entry_point
    return ep.load()
  File "/Users/jp/Library/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2369, in load
    return self.resolve()
  File "/Users/jp/Library/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2375, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.11-x86_64/egg/sqlite2json/__init__.py", line 40, in <module>
NameError: name 'exclude_tables' is not defined
```

**Comment by sneak** [comment]
after changing exclude_tables=exclude_tables on __init__.py:40, then:

```
tyrell:sms▻ sqlite2json sms.db
Traceback (most recent call last):
  File "/Users/jp/Library/homebrew/bin/sqlite2json", line 9, in <module>
    load_entry_point('sqlite2json==1.0.0', 'console_scripts', 'sqlite2json')()
  File "build/bdist.macosx-10.11-x86_64/egg/sqlite2json/__init__.py", line 25, in main
  File "build/bdist.macosx-10.11-x86_64/egg/sqlite2json/__init__.py", line 38, in sqlite2json
  File "build/bdist.macosx-10.11-x86_64/egg/sqlite2json/__init__.py", line 54, in get_tables
  File "build/bdist.macosx-10.11-x86_64/egg/sqlite2json/__init__.py", line 42, in get_table_list
TypeError: unsupported operand type(s) for -: 'set' and 'list'
```
