### ISSUE TITLE
Fails to read LICENSE

### ISSUE THREAD

**Issue by sr-verde** [john-g-g/sqlite2json#5]
The LICENSE file does not exist in the tar.
```
Collecting sqlite2json
  Using cached https://files.pythonhosted.org/packages/a0/ad/d913a4bbcc19f6194f10f7dee6da3e64e18bba8530e8da23f6b45536d813/sqlite2json-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-lIvGsP/sqlite2json/setup.py", line 10, in <module>
        license=open('LICENSE').read(),
    IOError: [Errno 2] No such file or directory: 'LICENSE'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lIvGsP/sqlite2json
```

**Comment by sneak** [comment]
Seconded:

```
nostromo:~/20191118.homedir/Library/Messages$ pip3 install --user sqlite2json
Collecting sqlite2json
  Downloading sqlite2json-1.0.1.tar.gz (8.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/sneak/.pyenv/versions/3.8.5/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qs/60qltk710tq2p7d34s1_tcbr0000gp/T/pip-install-50qka1bn/sqlite2json/setup.py'"'"'; __file__='"'"'/private/var/folders/qs/60qltk710tq2p7d34s1_tcbr0000gp/T/pip-install-50qka1bn/sqlite2json/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/qs/60qltk710tq2p7d34s1_tcbr0000gp/T/pip-pip-egg-info-d4uhql6y
         cwd: /private/var/folders/qs/60qltk710tq2p7d34s1_tcbr0000gp/T/pip-install-50qka1bn/sqlite2json/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qs/60qltk710tq2p7d34s1_tcbr0000gp/T/pip-install-50qka1bn/sqlite2json/setup.py", line 10, in <module>
        license=open('LICENSE').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/sneak/.pyenv/versions/3.8.5/bin/python -m pip install --upgrade pip' command.
```
